<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Catching exceptions in JavaScript | </title>
		
		<link rel="stylesheet" href="../../../../../tore/@/fonts/listΣ.css?v=1">
<link rel="stylesheet" href="../../../../../tore/layd/deff/&/aefb44b7dac371a3860e9079298a950e.ructΣ.css">
<link rel="stylesheet" href="../../../../../tore/&/2290bf7aeadc4261337d6f570a3cf0c5.apprΣ.css">

<script src="../../../../../tore/&/77748427269d1c81490f5acb6ce46fc1.apprΣ.js" defer></script>


<meta name="yandex-verification" content="00eb45b7559e5c68">
<meta name="google-site-verification" content="Af0TM2OrwIEtjoQXxYz2-1C-21E1m7DB23_kWpE9sLg">
<meta name="viewport" content="width=device-width, initial-scale=1.0">		
		<meta name="description" content="In this lesson, we will learn how to catch exceptions using the try-catch construct in JavaScript.">
		<link rel="shortcut icon" type="image/x-icon" href="../../../../../favicon.ico">
	</head>
	<body id="top" data-gq="D">
		<div data-r="ruct/wrap">
			<header>
				<div data-r="ruct/topp">
	<div data-r="topp/left">
		<div data-w="nict/logo">
	<img data-e="img" data-x src="" alt="">
</div>	</div>
	<div data-r="topp/righ">
		offline version v3	</div>
	<div data-r="topp/cent">
		<br><br>	</div>
</div>								
				<div data-r="ruct/navi">
					<div data-w="nict/over">
			<span data-e="hash" data-x>⊗jsSpExcCt</span>
				<span data-e="lofo" data-x>139 of 281</span>
				<a href="../../../../../en/javascript/book/supreme.html" data-e="link" data-x>menu</a>
	</div>					<nav data-w="nict/mainmenu">
	<section data-e="main" data-x data-gm-acte="T">
		<span data-q-href="/en/markup/" data-e="open" data-x data-m-targ="markup">Markup</span>
		<span data-q-href="/en/javascript/" data-e="open" data-x data-m-targ="javascript">JavaScript</span>
	</section>
	
	<section data-e="subb" data-x data-gm-acte="F" data-m-tabb="markup">
		<a href="../../../../../en/markup/manual/html.html">HTML manual</a>
		<a href="../../../../../en/markup/manual/css.html">CSS manual</a>
	</section>
	
	<section data-e="subb" data-x data-gm-acte="F" data-m-tabb="javascript">
		<a href="../../../../../en/javascript/book/prime.html">Prime book</a>
		<a href="../../../../../en/javascript/book/practice.html">Practice book</a>
		<a href="../../../../../en/javascript/book/supreme.html">Supreme book</a>
		<a href="../../../../../en/javascript/manual.html">Manual</a>
	</section>
</nav>									</div>
			</header>
			<main>
				<div data-w="nict/hett">
	<h1>Catching exceptions in JavaScript</h1>
</div>				<div data-p="cont/pane">
<p>
	The <code data-gs="comd/c" data-x>try-catch</code> construct is used 
	to catch exceptions. It has the following 
	syntax:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">try {
	// a code
} catch (error) {
	// an error handling
}</code>
</div>
<p>
	The <code data-gs="comd/c" data-x>try</code>-block should contain code 
	that may contain an exception. If suddenly 
	an exception occurs when executing this code, 
	then our script will not crash with an error 
	in the console, but the code of the 
	<code data-gs="comd/c" data-x>catch</code>-block will be executed.
</p>
<p>
	In this block, we must somehow adequately 
	react to the error. For example, if we 
	wanted to send some data via the Internet 
	and the Internet does not work, in a 
	<code data-gs="comd/c" data-x>catch</code>-block we can somehow handle 
	the situation: we can, for example, display 
	a message to an user, or we can try to send 
	this data again - suddenly the Internet is 
	already working.
</p>
<p>
	If, however, no exceptions occurred during 
	the execution of a <code data-gs="comd/c" data-x>try</code>-block, then 
	the useful code will simply be executed, 
	while the code from a <code data-gs="comd/c" data-x>catch</code> block will not.
</p>
<p>
	For example, let's try to parse JSON and, 
	if it is invalid, we will display a message 
	about it on the screen:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">try {
	let data = JSON.parse('{1,2,3,4,5}');
} catch (error) {
	alert('unable to parse JSON');
}</code>
</div>
<div data-w="cont/task">
	<p>
		Given a code that save some string 
		to a local storage:
	</p>
	<div data-p="bock/pane">
		<code data-w="bock/code" data-lo="high" data-m-lang="javascript">let str = 'some string';
localStorage.setItem('key', str);</code>
	</div>
	<p>
		Wrap this code in a <code data-gs="comd/c" data-x>try-catch</code> 
		construct. In the <code data-gs="comd/c" data-x>catch</code>-block, 
		display a message about storage 
		overflow. Test your code for a string 
		smaller than <code data-gs="comd/n" data-x>5</code> MB and for a 
		larger string.
	</p>
</div>
<div data-w="cont/task">
	<p>
		Given a JSON containing an array. If this 
		JSON is correct, then output the elements 
		of the array as a <code data-gs="comd/c" data-x>ul</code> list. If the 
		JSON is not valid, display a message on 
		the screen saying that an error has 
		occurred on the page.
	</p>
</div>
</div>			</main>
				<div data-w="nict/nebr">
					<a href="../../../../../en/javascript/book/supreme/exceptions/emerging-types.html" data-e="prev" data-x>
				<span data-e="arow" data-x>&larr;</span>
			</a>
							<a href="../../../../../en/javascript/book/supreme/exceptions/try-catch-development.html" data-e="next" data-x>
				<span data-e="arow" data-x>&rarr;</span>
			</a>
			</div>
			<footer data-w="ruct/foot">
				<div data-w="nict/finf">
	<span data-e="text" data-x>
		Trepachev Dmitry &copy; 2012-2024	</span>
	<br>
	<a data-e="link" data-x href="https://t.me/trepachev_dmitry">t.me/trepachev_dmitry</a>
</div>							</footer>
			<div data-w="nict/jump">
	<a href="#top"><span>&uarr;</span></a>
</div>			<div data-w="nict/lagr">
	<a href="../../../../../en/javascript/book/supreme/exceptions/catching.html" data-m-curr="T">en</a><a href="../../../../../ru/javascript/book/supreme/exceptions/catching.html" data-m-curr="F">ru</a></div>					</div>
		
		<script src="../../../../../tore/@/metrikaΣ.js?v=1"></script>	</body>
</html>